export const siteProjects = [
  {
    id: 1,
    key: "juliana" as const,
    name: "Juliana Goes",
    type: { pt: "Site institucional", en: "Institutional site", es: "Sitio institucional" },
    year: 2026,
    url: "https://www.julianagoes.com.br",
    featured: true,
    image: "/juliana-goes.webp",
    imageMobile: "/juliana-goes-mobile.webp",
    siteImage: "/juliana-goes-full.webp",
    siteImageMobile: "/juliana-goes-full-mobile.webp",
    tags: ["UI/UX Design", "Tipografia expressiva", "Identidade digital"],
  },
  {
    id: 2,
    key: "rm" as const,
    name: "Agência RM Digital",
    type: { pt: "Site institucional", en: "Institutional site", es: "Sitio institucional" },
    year: 2026,
    url: "https://www.agenciarmdigital.com.br",
    featured: false,
    image: "/rm-digital.webp",
    imageMobile: "/rm-digital-mobile.webp",
    siteImage: "/rm-digital-full.webp",
    siteImageMobile: "/rm-digital-full-mobile.webp",
    tags: ["UI/UX Design", "Branding digital", "Conversão"],
  },
  {
    id: 3,
    key: "ediane" as const,
    name: "Curso Trauma e Regulação",
    type: { pt: "Landing Page", en: "Landing Page", es: "Landing Page" },
    year: 2026,
    url: "https://curso-trauma-e-regulacao---ediane-ribei.webflow.io/",
    featured: false,
    image: "/trauma.webp",
    imageMobile: "/trauma-mobile.webp",
    siteImage: "/trauma-full.webp",
    siteImageMobile: "/trauma-full-mobile.webp",
    tags: ["Landing Page", "Identidade visual", "Conversão"],
  },
  {
    id: 4,
    key: "maison" as const,
    name: "Maison Aura Beauty",
    type: { pt: "Landing Page", en: "Landing Page", es: "Landing Page" },
    year: 2025,
    url: "https://www.maisonaurabeauty.com.br",
    featured: false,
    image: "/maison.webp",
    imageMobile: "/maison-mobile.webp",
    siteImage: "/maison-full.webp",
    siteImageMobile: "/maison-full-mobile.webp",
    tags: ["Landing Page", "Design elegante", "Conversão"],
  },
  {
    id: 5,
    key: "fagulha" as const,
    name: "Estúdio Fagulha",
    type: { pt: "Site institucional", en: "Institutional site", es: "Sitio institucional" },
    year: 2024,
    url: "https://estudiofagulha.com.br",
    featured: false,
    image: "/fagulha.webp",
    imageMobile: "/fagulha-mobile.webp",
    siteImage: "/fagulha-full.webp",
    siteImageMobile: "/fagulha-full-mobile.webp",
    tags: ["UI/UX Design", "Direção criativa", "Motion"],
  },
  {
    id: 6,
    key: "convi" as const,
    name: "Convi Foods",
    type: { pt: "Landing Page", en: "Landing Page", es: "Landing Page" },
    year: 2024,
    url: "https://convi-foods---landing-page.webflow.io",
    featured: false,
    image: "/convi.webp",
    imageMobile: "/convi-mobile.webp",
    siteImage: "/convi-full.webp",
    siteImageMobile: "/convi-full-mobile.webp",
    tags: ["Landing Page", "Copywriting visual", "Alta conversão"],
  },
  {
    id: 7,
    key: "aprovo" as const,
    name: "Aprovo Projetos",
    type: { pt: "Site institucional", en: "Institutional site", es: "Sitio institucional" },
    year: 2025,
    url: "https://www.aprovoprojetos.com.br",
    featured: false,
    image: "/aprovo.webp",
    imageMobile: "/aprovo-mobile.webp",
    siteImage: "/aprovo-full.webp",
    siteImageMobile: "/aprovo-full-mobile.webp",
    tags: ["UI/UX Design", "Arquitetura da informação", "Geração de leads"],
  },
];

export const brandingProjects = [
  {
    id: 8,
    key: "capitalconsorcio" as const,
    name: "Capital Consórcio",
    type: { pt: "Identidade Visual", en: "Visual Identity", es: "Identidad Visual" },
    year: 2026,
    url: "",
    featured: true,
    image: "/capitalconsorcio-desktop.webp",
    imageMobile: "/capitalconsorcio.webp",
    manualPages: Array.from({ length: 14 }, (_, i) => `/capitalconsorcio-manual/p${String(i + 1).padStart(2, "0")}.jpg`),
    tags: ["Logo", "Paleta de cores", "Tipografia", "Manual de marca"],
  },
  {
    id: 9,
    key: "traumaid" as const,
    name: "Curso Trauma e Regulação",
    type: { pt: "Identidade Visual", en: "Visual Identity", es: "Identidad Visual" },
    year: 2026,
    url: "",
    featured: false,
    image: "/trauma-id.webp",
    manual: "/trauma-manual.jpg",
    tags: ["Logo", "Identidade cromática", "Aplicações digitais", "Manual de marca"],
  },
  {
    id: 10,
    key: "continente" as const,
    name: "Continente Experience",
    type: { pt: "Identidade Visual", en: "Visual Identity", es: "Identidad Visual" },
    year: 2026,
    url: "",
    featured: false,
    image: "/continente.webp",
    manual: "/continente-manual.jpg",
    tags: ["Logo", "Identidade cromática", "Tipografia", "Manual de marca"],
  },
];

export type ProjectKey = typeof siteProjects[number]["key"] | typeof brandingProjects[number]["key"];
export type ProjectData = (typeof siteProjects[number] | typeof brandingProjects[number]) & {
  siteImage?: string;
  siteImageMobile?: string;
  manual?: string;
  manualPages?: string[];
};

export const allProjects: ProjectData[] = [...siteProjects, ...brandingProjects];

export function getProjectBySlug(slug: string): ProjectData | undefined {
  return allProjects.find((p) => p.key === slug);
}
